### ISSUE TITLE
Liftoff from haploid to diploid

### ISSUE THREAD

**Issue by pcarbone** [agshumate/Liftoff#22]
Thanks for this nice tool agshumate.

I am using Liftoff for lift-over of annotations from an haploid reference to a de novo diploid assembly produced with CanuTrio for another individual of the same species.
Would you recommend running Liftoff for each of the two de novo haplo-phases independently or for the diploid assembly together?
In the chroms.txt file, is a one-to-one relation needed or can one use the same reference chr in several entries?
E.g.:
chr01,chr01_maternal
chr01,chr01_paternal
chr02,chr02_maternal
chr02,chr02_paternal
...

Thank you!

**Comment by agshumate** [comment]
hi, there does not need to be a one-to-one relationship in the chroms.txt file so your example should work just fine! please let me know if you encounter any issues

**Comment by agshumate** [comment]
on second thought, i believe it would be better to run each haplo-phase individually. while there does not need to be a one-to-one mapping in the chroms.txt file, this only is useful if you still expect each gene to map to one location - for example mapping genes on human chromosome 2 to chimp chromosomes 2a and 2b. this is because liftoff by default only reports the single best mapping for each gene. 
In your cases you want 2 mappings for each gene so your best options are to run each haploid assembly separately, or to use the -copies option with a more lenient sequence identity threshold (-sc).

**Comment by pcarbone** [comment]
Thank you for your prompt answer and the pointers Alaina!
I expect two mappings for most reference genes. However, there is also presence-absence SV between haplo-phases in this species and this is why I thought that running Liftoff to the diploid assembly could be helpful in specific cases. I will try both strategies to compare.
