### ISSUE TITLE
Permit use of Winnomap (alternative to minimap2)

### ISSUE THREAD

**Issue by enormandeau** [agshumate/Liftoff#58]
Winnomap is built on top of minimap2 to ensure proper mapping of sequences in repetitive regions. Some species have a lot of repetitive regions and Winnomap outperforms minimap2 in these regions while providing similar quality in other regions.

Winnowmap code: https://github.com/marbl/Winnowmap
Winnowmap paper: https://www.biorxiv.org/content/10.1101/2020.11.01.363887v1.full

Winnowmap is not a drop-in replacement for minimap2, however, so the command cannot be simply substituted.

**Comment by flystar233** [comment]
Second!

**Comment by agshumate** [comment]
Looking into this it seems like it should work with the code already if you set -m to the winnowmap path and  then pre-generate the file of high-freq kmers and then use -mm2_options to pass in the file name. However when i test it, i get a segfault when trying to use an index of the target genome rather than just the target genome. Based on the documentation it looks like providing and index should work so i'm not sure why this happens. If either of you know what's up with this i'd appreciate your input. I can certainly work around this but it will require some code changes. 

Also just out of curiosity, which genome(s) are you working with? We got good results using liftoff with minimap2 for a wheat assembly and my assumption was that even though the genome as a whole was very repetitive, the gene sequences are unique enough to get good alignments (liftoff only aligns gene sequences to the target genome).

**Comment by enormandeau** [comment]
Feel free to close if this suggestion is not a priority.
